//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Task
{
    [Serializable]
    public class CabinetStateMsg : Message
    {
        public const string k_RosMessageName = "task_msgs/CabinetState";
        public override string RosMessageName => k_RosMessageName;

        // CabinetState.msg
        public byte cabinet_id;
        public MedicineDataMsg[] medicine_list;

        public CabinetStateMsg()
        {
            this.cabinet_id = 0;
            this.medicine_list = new MedicineDataMsg[0];
        }

        public CabinetStateMsg(byte cabinet_id, MedicineDataMsg[] medicine_list)
        {
            this.cabinet_id = cabinet_id;
            this.medicine_list = medicine_list;
        }

        public static CabinetStateMsg Deserialize(MessageDeserializer deserializer) => new CabinetStateMsg(deserializer);

        private CabinetStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cabinet_id);
            deserializer.Read(out this.medicine_list, MedicineDataMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cabinet_id);
            serializer.WriteLength(this.medicine_list);
            serializer.Write(this.medicine_list);
        }

        public override string ToString()
        {
            return "CabinetStateMsg: " +
            "\ncabinet_id: " + cabinet_id.ToString() +
            "\nmedicine_list: " + System.String.Join(", ", medicine_list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
