//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Task
{
    [Serializable]
    public class CabinetRunningMsg : Message
    {
        public const string k_RosMessageName = "task_msgs/CabinetRunning";
        public override string RosMessageName => k_RosMessageName;

        // CabinetRunning.msg
        public byte cabinet_id;
        public byte isrunning;

        public CabinetRunningMsg()
        {
            this.cabinet_id = 0;
            this.isrunning = 0;
        }

        public CabinetRunningMsg(byte cabinet_id, byte isrunning)
        {
            this.cabinet_id = cabinet_id;
            this.isrunning = isrunning;
        }

        public static CabinetRunningMsg Deserialize(MessageDeserializer deserializer) => new CabinetRunningMsg(deserializer);

        private CabinetRunningMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cabinet_id);
            deserializer.Read(out this.isrunning);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cabinet_id);
            serializer.Write(this.isrunning);
        }

        public override string ToString()
        {
            return "CabinetRunningMsg: " +
            "\ncabinet_id: " + cabinet_id.ToString() +
            "\nisrunning: " + isrunning.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
