//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Task
{
    [Serializable]
    public class MedicineDataMsg : Message
    {
        public const string k_RosMessageName = "task_msgs/MedicineData";
        public override string RosMessageName => k_RosMessageName;

        // MedicineData.msg
        public byte row;
        public byte column;
        public byte count;

        public MedicineDataMsg()
        {
            this.row = 0;
            this.column = 0;
            this.count = 0;
        }

        public MedicineDataMsg(byte row, byte column, byte count)
        {
            this.row = row;
            this.column = column;
            this.count = count;
        }

        public static MedicineDataMsg Deserialize(MessageDeserializer deserializer) => new MedicineDataMsg(deserializer);

        private MedicineDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.row);
            deserializer.Read(out this.column);
            deserializer.Read(out this.count);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.row);
            serializer.Write(this.column);
            serializer.Write(this.count);
        }

        public override string ToString()
        {
            return "MedicineDataMsg: " +
            "\nrow: " + row.ToString() +
            "\ncolumn: " + column.ToString() +
            "\ncount: " + count.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
