//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Task
{
    [Serializable]
    public class TaskMsg : Message
    {
        public const string k_RosMessageName = "task_msgs/Task";
        public override string RosMessageName => k_RosMessageName;

        //  Task.msg
        public string task_id;
        public CabinetOrderMsg[] cabinets;
        public string type;

        public TaskMsg()
        {
            this.task_id = "";
            this.cabinets = new CabinetOrderMsg[0];
            this.type = "";
        }

        public TaskMsg(string task_id, CabinetOrderMsg[] cabinets, string type)
        {
            this.task_id = task_id;
            this.cabinets = cabinets;
            this.type = type;
        }

        public static TaskMsg Deserialize(MessageDeserializer deserializer) => new TaskMsg(deserializer);

        private TaskMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.cabinets, CabinetOrderMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.WriteLength(this.cabinets);
            serializer.Write(this.cabinets);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "TaskMsg: " +
            "\ntask_id: " + task_id.ToString() +
            "\ncabinets: " + System.String.Join(", ", cabinets.ToList()) +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
