//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class PositionMsg : Message
    {
        public const string k_RosMessageName = "Assets/Position";
        public override string RosMessageName => k_RosMessageName;

        //  Position.msg
        public byte row;
        public byte column;

        public PositionMsg()
        {
            this.row = 0;
            this.column = 0;
        }

        public PositionMsg(byte row, byte column)
        {
            this.row = row;
            this.column = column;
        }

        public static PositionMsg Deserialize(MessageDeserializer deserializer) => new PositionMsg(deserializer);

        private PositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.row);
            deserializer.Read(out this.column);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.row);
            serializer.Write(this.column);
        }

        public override string ToString()
        {
            return "PositionMsg: " +
            "\nrow: " + row.ToString() +
            "\ncolumn: " + column.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
