"""
批量药品种子数据生成脚本
生成 100+ 种涵盖 12 大类的药品，每种药附带适应症信息。
幂等执行：每次运行先清空再重新写入。

用法：python3 -m database.scripts.seed_drugs
"""

import sqlite3
import random
import itertools
from datetime import date, datetime, timezone

from common.config import Config

DB_PATH = Config.DATABASE_PATH


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# 第一周：药品数据定义（含扩展字段：strength/generic_name/dosage_form/manufacturer/drug_interactions/age_restrictions）

DRUG_CATEGORIES = [
    {
        "category": "解热镇痛抗炎药",
        "manufacturer": "华润双鹤药业股份有限公司",
        "drug_interactions": '["避免与其他NSAIDs同时使用", "与抗凝药合用需监测出血风险", "避免与酒精同服"]',
        "age_restrictions": '{"min": 6}',
        "drugs": [
            {
                "name": "布洛芬",
                "generic_name": "ibuprofen",
                "strength": "200mg",
                "dosage_form": "片剂",
                "indications": ["头痛","头疼","偏头痛","牙痛","关节痛","痛经","发热","发烧","肌肉痛"],
                "is_prescription": False, "price": 15.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "对乙酰氨基酚",
                "generic_name": "acetaminophen",
                "strength": "500mg",
                "dosage_form": "片剂",
                "indications": ["发热","发烧","头痛","头疼","关节痛","肌肉痛","感冒"],
                "is_prescription": False, "price": 10.0,
                "min_stock": 80, "max_stock": 300,
            },
            {
                "name": "阿司匹林",
                "generic_name": "aspirin",
                "strength": "100mg",
                "dosage_form": "肠溶片",
                "indications": ["发热","发烧","头痛","关节痛","心血管疾病","预防血栓"],
                "is_prescription": True, "price": 8.0,
                "min_stock": 60, "max_stock": 200,
            },
            {
                "name": "双氯芬酸",
                "generic_name": "diclofenac",
                "strength": "50mg",
                "dosage_form": "肠溶片",
                "indications": ["关节痛","肌肉痛","腰痛","关节炎","扭伤","痛风"],
                "is_prescription": True, "price": 18.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "塞来昔布",
                "generic_name": "celecoxib",
                "strength": "200mg",
                "dosage_form": "胶囊",
                "indications": ["关节炎","关节痛","腰痛","骨关节炎","强直性脊柱炎"],
                "is_prescription": True, "price": 45.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "洛索洛芬",
                "generic_name": "loxoprofen",
                "strength": "60mg",
                "dosage_form": "片剂",
                "indications": ["头痛","牙痛","关节痛","肌肉痛","腰痛","手术后疼痛"],
                "is_prescription": True, "price": 22.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "依托考昔",
                "generic_name": "etoricoxib",
                "strength": "60mg",
                "dosage_form": "片剂",
                "indications": ["关节炎","关节痛","痛风","腰痛","骨关节炎"],
                "is_prescription": True, "price": 50.0,
                "min_stock": 15, "max_stock": 60,
            },
            {
                "name": "萘普生",
                "generic_name": "naproxen",
                "strength": "250mg",
                "dosage_form": "片剂",
                "indications": ["头痛","牙痛","关节痛","肌肉痛","痛经","发热"],
                "is_prescription": False, "price": 12.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "美洛昔康",
                "generic_name": "meloxicam",
                "strength": "7.5mg",
                "dosage_form": "片剂",
                "indications": ["关节炎","关节痛","腰痛","骨关节炎","类风湿关节炎"],
                "is_prescription": True, "price": 28.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "吲哚美辛",
                "generic_name": "indomethacin",
                "strength": "25mg",
                "dosage_form": "胶囊",
                "indications": ["关节炎","痛风","腰痛","强直性脊柱炎","关节痛"],
                "is_prescription": True, "price": 10.0,
                "min_stock": 25, "max_stock": 90,
            },
        ],
    },
    {
        "category": "抗生素抗感染药",
        "manufacturer": "哈药集团制药总厂",
        "drug_interactions": '["避免与制酸药同服（间隔2小时）", "与华法林合用需监测INR", "避免与抗癫痫药同用"]',
        "age_restrictions": '{"min": 0}',
        "drugs": [
            {
                "name": "阿莫西林",
                "generic_name": "amoxicillin",
                "strength": "250mg",
                "dosage_form": "胶囊",
                "indications": ["感冒","发热","发烧","呼吸道感染","扁桃体炎","中耳炎","鼻窦炎"],
                "is_prescription": True, "price": 12.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "头孢克肟",
                "generic_name": "cefixime",
                "strength": "100mg",
                "dosage_form": "胶囊",
                "indications": ["呼吸道感染","泌尿道感染","皮肤感染","扁桃体炎","中耳炎"],
                "is_prescription": True, "price": 35.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "头孢拉定",
                "generic_name": "cefradine",
                "strength": "250mg",
                "dosage_form": "胶囊",
                "indications": ["呼吸道感染","泌尿道感染","皮肤感染","扁桃体炎"],
                "is_prescription": True, "price": 20.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "头孢氨苄",
                "generic_name": "cefalexin",
                "strength": "250mg",
                "dosage_form": "胶囊",
                "indications": ["呼吸道感染","皮肤感染","泌尿道感染","扁桃体炎"],
                "is_prescription": True, "price": 15.0,
                "min_stock": 35, "max_stock": 120,
            },
            {
                "name": "阿奇霉素",
                "generic_name": "azithromycin",
                "strength": "250mg",
                "dosage_form": "胶囊",
                "indications": ["呼吸道感染","肺炎","支气管炎","咽炎","皮肤感染"],
                "is_prescription": True, "price": 40.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "左氧氟沙星",
                "generic_name": "levofloxacin",
                "strength": "250mg",
                "dosage_form": "片剂",
                "indications": ["呼吸道感染","泌尿道感染","肠道感染","前列腺炎","皮肤感染"],
                "is_prescription": True, "price": 30.0,
                "min_stock": 25, "max_stock": 90,
            },
            {
                "name": "克拉霉素",
                "generic_name": "clarithromycin",
                "strength": "250mg",
                "dosage_form": "片剂",
                "indications": ["呼吸道感染","支气管炎","肺炎","鼻窦炎","皮肤感染"],
                "is_prescription": True, "price": 35.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "甲硝唑",
                "generic_name": "metronidazole",
                "strength": "200mg",
                "dosage_form": "片剂",
                "indications": ["牙痛","牙周炎","牙龈炎","肠道感染","阴道感染"],
                "is_prescription": True, "price": 8.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "诺氟沙星",
                "generic_name": "norfloxacin",
                "strength": "100mg",
                "dosage_form": "胶囊",
                "indications": ["腹泻","肠道感染","泌尿道感染","细菌性痢疾"],
                "is_prescription": True, "price": 10.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "克林霉素",
                "generic_name": "clindamycin",
                "strength": "150mg",
                "dosage_form": "胶囊",
                "indications": ["皮肤感染","呼吸道感染","骨感染","牙周感染"],
                "is_prescription": True, "price": 25.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "罗红霉素",
                "generic_name": "roxithromycin",
                "strength": "150mg",
                "dosage_form": "片剂",
                "indications": ["呼吸道感染","支气管炎","肺炎","咽炎","皮肤感染"],
                "is_prescription": True, "price": 28.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "头孢呋辛",
                "generic_name": "cefuroxime",
                "strength": "250mg",
                "dosage_form": "片剂",
                "indications": ["呼吸道感染","泌尿道感染","皮肤感染","中耳炎","鼻窦炎"],
                "is_prescription": True, "price": 32.0,
                "min_stock": 20, "max_stock": 70,
            },
            {
                "name": "阿莫西林克拉维酸",
                "generic_name": "amoxicillin/clavulanate",
                "strength": "625mg",
                "dosage_form": "片剂",
                "indications": ["呼吸道感染","鼻窦炎","中耳炎","皮肤感染","泌尿道感染"],
                "is_prescription": True, "price": 45.0,
                "min_stock": 15, "max_stock": 60,
            },
            {
                "name": "呋喃妥因",
                "generic_name": "nitrofurantoin",
                "strength": "50mg",
                "dosage_form": "肠溶片",
                "indications": ["泌尿道感染","膀胱炎","尿路感染"],
                "is_prescription": True, "price": 12.0,
                "min_stock": 25, "max_stock": 90,
            },
            {
                "name": "磷霉素",
                "generic_name": "fosfomycin",
                "strength": "500mg",
                "dosage_form": "颗粒剂",
                "indications": ["肠道感染","泌尿道感染","细菌性痢疾","腹泻"],
                "is_prescription": True, "price": 18.0,
                "min_stock": 20, "max_stock": 70,
            },
        ],
    },
    {
        "category": "消化系统药",
        "manufacturer": "扬子江药业集团有限公司",
        "drug_interactions": '["质子泵抑制剂可影响其他药物吸收", "避免与含铝镁制酸药同用"]',
        "age_restrictions": '{"min": 3}',
        "drugs": [
            {
                "name": "蒙脱石散",
                "generic_name": "smectite",
                "strength": "3g/袋",
                "dosage_form": "散剂",
                "indications": ["腹泻","拉肚子","拉稀","肠胃不适","急性胃肠炎"],
                "is_prescription": False, "price": 20.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "奥美拉唑",
                "generic_name": "omeprazole",
                "strength": "20mg",
                "dosage_form": "肠溶胶囊",
                "indications": ["胃痛","胃酸","反酸","胃食管反流","胃炎","胃溃疡"],
                "is_prescription": False, "price": 25.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "多潘立酮",
                "generic_name": "domperidone",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["恶心","想吐","呕吐","腹胀","消化不良","胃胀"],
                "is_prescription": False, "price": 15.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "铝碳酸镁",
                "generic_name": "hydrotalcite",
                "strength": "500mg",
                "dosage_form": "咀嚼片",
                "indications": ["胃痛","胃酸","反酸","胃灼热","胃炎","消化不良"],
                "is_prescription": False, "price": 18.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "雷贝拉唑",
                "generic_name": "rabeprazole",
                "strength": "10mg",
                "dosage_form": "肠溶片",
                "indications": ["胃痛","胃酸","反酸","胃食管反流","胃炎","胃溃疡"],
                "is_prescription": True, "price": 38.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "枸橼酸铋钾",
                "generic_name": "bismuth potassium citrate",
                "strength": "120mg",
                "dosage_form": "片剂",
                "indications": ["胃痛","胃炎","胃溃疡","胃酸","消化不良"],
                "is_prescription": False, "price": 22.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "莫沙必利",
                "generic_name": "mosapride",
                "strength": "5mg",
                "dosage_form": "片剂",
                "indications": ["腹胀","消化不良","胃胀","便秘","恶心","食欲不振"],
                "is_prescription": True, "price": 28.0,
                "min_stock": 20, "max_stock": 70,
            },
            {
                "name": "双歧杆菌",
                "generic_name": "bifidobacterium",
                "strength": "0.5g/粒",
                "dosage_form": "胶囊",
                "indications": ["腹泻","便秘","腹胀","消化不良","肠胃不适","肠道菌群失调"],
                "is_prescription": False, "price": 35.0,
                "min_stock": 25, "max_stock": 80,
            },
            {
                "name": "乳果糖",
                "generic_name": "lactulose",
                "strength": "15ml/袋",
                "dosage_form": "口服液",
                "indications": ["便秘","排便困难","老年便秘","习惯性便秘"],
                "is_prescription": False, "price": 30.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "开塞露",
                "generic_name": "glycerin",
                "strength": "20ml/支",
                "dosage_form": "外用液",
                "indications": ["便秘","排便困难","大便干结"],
                "is_prescription": False, "price": 5.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "泮托拉唑",
                "generic_name": "pantoprazole",
                "strength": "40mg",
                "dosage_form": "肠溶片",
                "indications": ["胃痛","胃酸","胃溃疡","胃食管反流","胃炎"],
                "is_prescription": True, "price": 35.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "复方消化酶",
                "generic_name": "compound digestive enzyme",
                "strength": "1片/次",
                "dosage_form": "肠溶片",
                "indications": ["消化不良","腹胀","食欲不振","胃胀","肠胃不适"],
                "is_prescription": False, "price": 25.0,
                "min_stock": 20, "max_stock": 70,
            },
        ],
    },
    {
        "category": "呼吸系统药",
        "manufacturer": "正大天晴药业集团股份有限公司",
        "drug_interactions": '["β受体激动剂与茶碱合用需监测心率", "吸入性糖皮质激素长期使用需监测骨密度"]',
        "age_restrictions": '{"min": 2}',
        "drugs": [
            {
                "name": "氨溴索",
                "generic_name": "ambroxol",
                "strength": "30mg",
                "dosage_form": "片剂",
                "indications": ["咳嗽","咳痰","痰多","支气管炎","咽喉痛","呼吸道感染"],
                "is_prescription": False, "price": 12.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "右美沙芬",
                "generic_name": "dextromethorphan",
                "strength": "15mg",
                "dosage_form": "片剂",
                "indications": ["咳嗽","干咳","感冒咳嗽","咽炎"],
                "is_prescription": False, "price": 15.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "沙丁胺醇",
                "generic_name": "salbutamol",
                "strength": "100mcg/揿",
                "dosage_form": "气雾剂",
                "indications": ["哮喘","气喘","呼吸困难","支气管痉挛","咳嗽","胸闷"],
                "is_prescription": True, "price": 25.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "复方甘草片",
                "generic_name": "compound liquorice tablet",
                "strength": "1片",
                "dosage_form": "片剂",
                "indications": ["咳嗽","咳痰","咽喉痛","支气管炎","感冒咳嗽"],
                "is_prescription": False, "price": 8.0,
                "min_stock": 40, "max_stock": 200,
            },
            {
                "name": "孟鲁司特",
                "generic_name": "montelukast",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["哮喘","过敏性鼻炎","咳嗽","气喘","呼吸困难"],
                "is_prescription": True, "price": 40.0,
                "min_stock": 15, "max_stock": 60,
            },
            {
                "name": "茶碱",
                "generic_name": "theophylline",
                "strength": "100mg",
                "dosage_form": "缓释片",
                "indications": ["哮喘","气喘","支气管炎","呼吸困难","慢性阻塞性肺病"],
                "is_prescription": True, "price": 18.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "异丙托溴铵",
                "generic_name": "ipratropium bromide",
                "strength": "20mcg/揿",
                "dosage_form": "气雾剂",
                "indications": ["哮喘","气喘","呼吸困难","支气管炎","慢性阻塞性肺病"],
                "is_prescription": True, "price": 30.0,
                "min_stock": 15, "max_stock": 60,
            },
            {
                "name": "乙酰半胱氨酸",
                "generic_name": "acetylcysteine",
                "strength": "600mg",
                "dosage_form": "泡腾片",
                "indications": ["咳嗽","咳痰","痰多","支气管炎","呼吸道感染"],
                "is_prescription": False, "price": 22.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "福莫特罗",
                "generic_name": "formoterol",
                "strength": "12mcg/粒",
                "dosage_form": "吸入粉雾剂",
                "indications": ["哮喘","气喘","呼吸困难","支气管痉挛","慢性阻塞性肺病"],
                "is_prescription": True, "price": 55.0,
                "min_stock": 10, "max_stock": 50,
            },
            {
                "name": "布地奈德",
                "generic_name": "budesonide",
                "strength": "200mcg/揿",
                "dosage_form": "气雾剂",
                "indications": ["哮喘","过敏性鼻炎","气喘","呼吸困难","慢性阻塞性肺病"],
                "is_prescription": True, "price": 60.0,
                "min_stock": 10, "max_stock": 50,
            },
        ],
    },
    {
        "category": "抗过敏药",
        "manufacturer": "西安杨森制药有限公司",
        "drug_interactions": '["避免与中枢神经系统抑制剂同用", "与酒精同服可加重嗜睡"]',
        "age_restrictions": '{"min": 2}',
        "drugs": [
            {
                "name": "氯雷他定",
                "generic_name": "loratadine",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["过敏性鼻炎","荨麻疹","皮肤瘙痒","过敏","皮肤过敏","皮疹","打喷嚏","流鼻涕"],
                "is_prescription": False, "price": 20.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "西替利嗪",
                "generic_name": "cetirizine",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["过敏性鼻炎","荨麻疹","皮肤瘙痒","过敏","皮肤过敏","皮疹"],
                "is_prescription": False, "price": 18.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "扑尔敏",
                "generic_name": "chlorphenamine",
                "strength": "4mg",
                "dosage_form": "片剂",
                "indications": ["过敏性鼻炎","荨麻疹","皮肤瘙痒","过敏","打喷嚏","流鼻涕","感冒"],
                "is_prescription": False, "price": 5.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "依巴斯汀",
                "generic_name": "ebastine",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["过敏性鼻炎","荨麻疹","皮肤瘙痒","过敏","皮肤过敏"],
                "is_prescription": False, "price": 25.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "非索非那定",
                "generic_name": "fexofenadine",
                "strength": "120mg",
                "dosage_form": "片剂",
                "indications": ["过敏性鼻炎","荨麻疹","皮肤瘙痒","过敏","打喷嚏","流鼻涕"],
                "is_prescription": False, "price": 30.0,
                "min_stock": 20, "max_stock": 70,
            },
            {
                "name": "酮替芬",
                "generic_name": "ketotifen",
                "strength": "1mg",
                "dosage_form": "片剂",
                "indications": ["过敏性鼻炎","荨麻疹","皮肤瘙痒","过敏","哮喘","咳嗽"],
                "is_prescription": True, "price": 12.0,
                "min_stock": 25, "max_stock": 90,
            },
        ],
    },
    {
        "category": "心血管药",
        "manufacturer": "北京诺华制药有限公司",
        "drug_interactions": '["CCB与β受体阻滞剂合用需监测心率和血压", "他汀类与贝特类合用需监测肌酸激酶", "ACEI/ARB避免联合使用"]',
        "age_restrictions": '{"min": 18}',
        "drugs": [
            {
                "name": "硝苯地平",
                "generic_name": "nifedipine",
                "strength": "10mg",
                "dosage_form": "控释片",
                "indications": ["高血压","血压高","心绞痛","冠心病"],
                "is_prescription": True, "price": 15.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "厄贝沙坦",
                "generic_name": "irbesartan",
                "strength": "150mg",
                "dosage_form": "片剂",
                "indications": ["高血压","血压高","肾病","糖尿病肾病"],
                "is_prescription": True, "price": 28.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "美托洛尔",
                "generic_name": "metoprolol",
                "strength": "50mg",
                "dosage_form": "缓释片",
                "indications": ["高血压","血压高","心绞痛","心力衰竭","心律失常","心悸"],
                "is_prescription": True, "price": 18.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "氨氯地平",
                "generic_name": "amlodipine",
                "strength": "5mg",
                "dosage_form": "片剂",
                "indications": ["高血压","血压高","心绞痛","冠心病"],
                "is_prescription": True, "price": 25.0,
                "min_stock": 35, "max_stock": 120,
            },
            {
                "name": "缬沙坦",
                "generic_name": "valsartan",
                "strength": "80mg",
                "dosage_form": "胶囊",
                "indications": ["高血压","血压高","心力衰竭","肾病"],
                "is_prescription": True, "price": 30.0,
                "min_stock": 25, "max_stock": 100,
            },
            {
                "name": "卡托普利",
                "generic_name": "captopril",
                "strength": "25mg",
                "dosage_form": "片剂",
                "indications": ["高血压","血压高","心力衰竭","肾病"],
                "is_prescription": True, "price": 12.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "氯沙坦",
                "generic_name": "losartan",
                "strength": "50mg",
                "dosage_form": "片剂",
                "indications": ["高血压","血压高","肾病","糖尿病肾病"],
                "is_prescription": True, "price": 32.0,
                "min_stock": 25, "max_stock": 90,
            },
            {
                "name": "阿托伐他汀",
                "generic_name": "atorvastatin",
                "strength": "20mg",
                "dosage_form": "片剂",
                "indications": ["高血脂","高胆固醇","冠心病","动脉粥样硬化","心血管疾病"],
                "is_prescription": True, "price": 45.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "辛伐他汀",
                "generic_name": "simvastatin",
                "strength": "20mg",
                "dosage_form": "片剂",
                "indications": ["高血脂","高胆固醇","冠心病","动脉粥样硬化"],
                "is_prescription": True, "price": 20.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "非洛地平",
                "generic_name": "felodipine",
                "strength": "5mg",
                "dosage_form": "缓释片",
                "indications": ["高血压","血压高","心绞痛"],
                "is_prescription": True, "price": 22.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "普伐他汀",
                "generic_name": "pravastatin",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["高血脂","高胆固醇","冠心病","动脉粥样硬化"],
                "is_prescription": True, "price": 35.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "比索洛尔",
                "generic_name": "bisoprolol",
                "strength": "5mg",
                "dosage_form": "片剂",
                "indications": ["高血压","血压高","心绞痛","心力衰竭","心律失常","心悸"],
                "is_prescription": True, "price": 28.0,
                "min_stock": 20, "max_stock": 80,
            },
        ],
    },
    {
        "category": "内分泌代谢药",
        "manufacturer": "北京协和药厂",
        "drug_interactions": '["二甲双胍避免与含碘造影剂同用", "胰岛素促分泌剂与其他降糖药合用需警惕低血糖", "甲状腺素制剂避免与含钙补充剂同服（间隔4小时）"]',
        "age_restrictions": '{"min": 18}',
        "drugs": [
            {
                "name": "二甲双胍",
                "generic_name": "metformin",
                "strength": "500mg",
                "dosage_form": "肠溶片",
                "indications": ["糖尿病","血糖高","2型糖尿病","多囊卵巢综合征"],
                "is_prescription": True, "price": 10.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "格列美脲",
                "generic_name": "glimepiride",
                "strength": "2mg",
                "dosage_form": "片剂",
                "indications": ["糖尿病","血糖高","2型糖尿病"],
                "is_prescription": True, "price": 25.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "左甲状腺素",
                "generic_name": "levothyroxine",
                "strength": "50mcg",
                "dosage_form": "片剂",
                "indications": ["甲状腺功能减退","甲减","甲状腺肿大"],
                "is_prescription": True, "price": 20.0,
                "min_stock": 25, "max_stock": 90,
            },
            {
                "name": "阿卡波糖",
                "generic_name": "acarbose",
                "strength": "50mg",
                "dosage_form": "片剂",
                "indications": ["糖尿病","血糖高","2型糖尿病","餐后血糖高"],
                "is_prescription": True, "price": 35.0,
                "min_stock": 15, "max_stock": 60,
            },
            {
                "name": "格列齐特",
                "generic_name": "gliclazide",
                "strength": "80mg",
                "dosage_form": "缓释片",
                "indications": ["糖尿病","血糖高","2型糖尿病"],
                "is_prescription": True, "price": 22.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "瑞格列奈",
                "generic_name": "repaglinide",
                "strength": "1mg",
                "dosage_form": "片剂",
                "indications": ["糖尿病","血糖高","2型糖尿病","餐后血糖高"],
                "is_prescription": True, "price": 30.0,
                "min_stock": 15, "max_stock": 60,
            },
            {
                "name": "西格列汀",
                "generic_name": "sitagliptin",
                "strength": "100mg",
                "dosage_form": "片剂",
                "indications": ["糖尿病","血糖高","2型糖尿病"],
                "is_prescription": True, "price": 55.0,
                "min_stock": 10, "max_stock": 50,
            },
            {
                "name": "吡格列酮",
                "generic_name": "pioglitazone",
                "strength": "15mg",
                "dosage_form": "片剂",
                "indications": ["糖尿病","血糖高","2型糖尿病"],
                "is_prescription": True, "price": 40.0,
                "min_stock": 15, "max_stock": 60,
            },
        ],
    },
    {
        "category": "神经系统药",
        "manufacturer": "远大医药（中国）有限公司",
        "drug_interactions": '["苯二氮䓬类避免与酒精同服", "与其他中枢神经系统抑制剂合用可增加镇静效果", "MAO抑制剂与抗抑郁药合用需谨慎"]',
        "age_restrictions": '{"min": 18}',
        "drugs": [
            {
                "name": "艾司唑仑",
                "generic_name": "estazolam",
                "strength": "1mg",
                "dosage_form": "片剂",
                "indications": ["失眠","睡不着","入睡困难","焦虑","睡眠障碍"],
                "is_prescription": True, "price": 12.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "地西泮",
                "generic_name": "diazepam",
                "strength": "5mg",
                "dosage_form": "片剂",
                "indications": ["焦虑","失眠","紧张","惊厥","肌肉痉挛","烦躁"],
                "is_prescription": True, "price": 8.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "阿普唑仑",
                "generic_name": "alprazolam",
                "strength": "0.4mg",
                "dosage_form": "片剂",
                "indications": ["焦虑","紧张","失眠","惊恐","烦躁"],
                "is_prescription": True, "price": 15.0,
                "min_stock": 15, "max_stock": 60,
            },
            {
                "name": "氟桂利嗪",
                "generic_name": "flunarizine",
                "strength": "5mg",
                "dosage_form": "胶囊",
                "indications": ["偏头痛","头痛","眩晕","头晕","耳鸣"],
                "is_prescription": True, "price": 20.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "谷维素",
                "generic_name": "oryzanol",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["失眠","焦虑","神经衰弱","植物神经紊乱","头痛","头晕"],
                "is_prescription": False, "price": 8.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "甲钴胺",
                "generic_name": "mecobalamin",
                "strength": "500mcg",
                "dosage_form": "片剂",
                "indications": ["神经痛","神经炎","麻木","周围神经病变","贫血"],
                "is_prescription": False, "price": 15.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "维生素B1",
                "generic_name": "thiamine",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["神经炎","神经痛","麻木","食欲不振","疲劳","脚气病"],
                "is_prescription": False, "price": 5.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "帕罗西汀",
                "generic_name": "paroxetine",
                "strength": "20mg",
                "dosage_form": "片剂",
                "indications": ["抑郁","焦虑","强迫症","惊恐","社交焦虑"],
                "is_prescription": True, "price": 55.0,
                "min_stock": 15, "max_stock": 50,
            },
        ],
    },
    {
        "category": "维生素矿物质",
        "manufacturer": "国药控股股份有限公司",
        "drug_interactions": '["维生素C大剂量可影响尿酸检测", "钙与铁剂避免同服（间隔2小时）", "叶酸与甲氨蝶呤有拮抗作用"]',
        "age_restrictions": '{"min": 0}',
        "drugs": [
            {
                "name": "维生素C",
                "generic_name": "ascorbic acid",
                "strength": "100mg",
                "dosage_form": "片剂",
                "indications": ["免疫力低下","坏血病","口腔溃疡","感冒","疲劳","牙龈出血"],
                "is_prescription": False, "price": 5.0,
                "min_stock": 100, "max_stock": 500,
            },
            {
                "name": "维生素D",
                "generic_name": "cholecalciferol",
                "strength": "400IU",
                "dosage_form": "胶囊",
                "indications": ["骨质疏松","钙缺乏","佝偻病","免疫力低下","骨折"],
                "is_prescription": False, "price": 15.0,
                "min_stock": 60, "max_stock": 300,
            },
            {
                "name": "维生素B6",
                "generic_name": "pyridoxine",
                "strength": "10mg",
                "dosage_form": "片剂",
                "indications": ["呕吐","孕吐","神经炎","皮肤炎症","贫血","恶心"],
                "is_prescription": False, "price": 5.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "维生素B12",
                "generic_name": "cyanocobalamin",
                "strength": "25mcg",
                "dosage_form": "片剂",
                "indications": ["贫血","疲劳","神经炎","神经痛","麻木","口腔溃疡"],
                "is_prescription": False, "price": 8.0,
                "min_stock": 40, "max_stock": 180,
            },
            {
                "name": "钙片",
                "generic_name": "calcium carbonate",
                "strength": "500mg",
                "dosage_form": "咀嚼片",
                "indications": ["骨质疏松","钙缺乏","骨折","抽筋","佝偻病","关节痛"],
                "is_prescription": False, "price": 30.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "复合维生素",
                "generic_name": "multivitamins",
                "strength": "1片/次",
                "dosage_form": "片剂",
                "indications": ["疲劳","免疫力低下","食欲不振","营养不良","维生素缺乏"],
                "is_prescription": False, "price": 45.0,
                "min_stock": 30, "max_stock": 150,
            },
            {
                "name": "铁剂",
                "generic_name": "ferrous sulfate",
                "strength": "300mg",
                "dosage_form": "肠溶片",
                "indications": ["贫血","缺铁性贫血","头晕","疲劳","面色苍白"],
                "is_prescription": False, "price": 25.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "锌剂",
                "generic_name": "zinc gluconate",
                "strength": "70mg",
                "dosage_form": "片剂",
                "indications": ["口腔溃疡","免疫力低下","食欲不振","生长发育迟缓","腹泻"],
                "is_prescription": False, "price": 20.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "叶酸",
                "generic_name": "folic acid",
                "strength": "0.4mg",
                "dosage_form": "片剂",
                "indications": ["贫血","备孕","孕期保健","胎儿神经管畸形预防","巨幼细胞性贫血"],
                "is_prescription": False, "price": 10.0,
                "min_stock": 40, "max_stock": 200,
            },
            {
                "name": "维生素E",
                "generic_name": "tocopherol",
                "strength": "100mg",
                "dosage_form": "胶囊",
                "indications": ["皮肤干燥","抗氧化","不孕不育","习惯性流产","肌肉萎缩"],
                "is_prescription": False, "price": 12.0,
                "min_stock": 30, "max_stock": 150,
            },
        ],
    },
    {
        "category": "外用药皮肤科",
        "manufacturer": "天津药业集团有限公司",
        "drug_interactions": '["含激素外用药长期使用需监测皮肤萎缩", "抗真菌药与激素联合使用需遵医嘱"]',
        "age_restrictions": '{"min": 2}',
        "drugs": [
            {
                "name": "莫匹罗星软膏",
                "generic_name": "mupirocin",
                "strength": "2%",
                "dosage_form": "软膏",
                "indications": ["皮肤感染","毛囊炎","疖子","皮肤破损","湿疹感染","脓疱疮"],
                "is_prescription": False, "price": 18.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "酮康唑乳膏",
                "generic_name": "ketoconazole",
                "strength": "2%",
                "dosage_form": "乳膏",
                "indications": ["皮肤癣","脚气","体癣","股癣","花斑癣","真菌感染"],
                "is_prescription": False, "price": 15.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "氢化可的松软膏",
                "generic_name": "hydrocortisone",
                "strength": "1%",
                "dosage_form": "软膏",
                "indications": ["皮肤瘙痒","湿疹","皮炎","过敏","皮疹","皮肤红肿"],
                "is_prescription": False, "price": 10.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "红霉素软膏",
                "generic_name": "erythromycin",
                "strength": "1%",
                "dosage_form": "软膏",
                "indications": ["皮肤感染","毛囊炎","疖子","烧伤感染","皮肤破损","痤疮"],
                "is_prescription": False, "price": 8.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "阿昔洛韦软膏",
                "generic_name": "acyclovir",
                "strength": "3%",
                "dosage_form": "软膏",
                "indications": ["带状疱疹","单纯疱疹","水痘","病毒性皮肤病","唇疱疹"],
                "is_prescription": False, "price": 12.0,
                "min_stock": 25, "max_stock": 90,
            },
            {
                "name": "特比萘芬乳膏",
                "generic_name": "terbinafine",
                "strength": "1%",
                "dosage_form": "乳膏",
                "indications": ["脚气","体癣","股癣","手癣","真菌感染","皮肤癣"],
                "is_prescription": False, "price": 20.0,
                "min_stock": 20, "max_stock": 80,
            },
            {
                "name": "炉甘石洗剂",
                "generic_name": "calamine lotion",
                "strength": "15%",
                "dosage_form": "洗剂",
                "indications": ["皮肤瘙痒","皮疹","荨麻疹","蚊虫叮咬","湿疹","过敏"],
                "is_prescription": False, "price": 8.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "复方醋酸地塞米松乳膏",
                "generic_name": "dexamethasone acetate compound",
                "strength": "0.025%",
                "dosage_form": "乳膏",
                "indications": ["湿疹","皮炎","皮肤瘙痒","过敏","皮疹","神经性皮炎"],
                "is_prescription": False, "price": 10.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "尿素软膏",
                "generic_name": "urea",
                "strength": "20%",
                "dosage_form": "软膏",
                "indications": ["皮肤干燥","手足皲裂","皮肤粗糙","鱼鳞病","角质增生"],
                "is_prescription": False, "price": 6.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "克霉唑乳膏",
                "generic_name": "clotrimazole",
                "strength": "1%",
                "dosage_form": "乳膏",
                "indications": ["真菌感染","脚气","体癣","股癣","阴道感染","皮肤癣"],
                "is_prescription": False, "price": 10.0,
                "min_stock": 25, "max_stock": 100,
            },
        ],
    },
    {
        "category": "中成药感冒类",
        "manufacturer": "广州白云山制药股份有限公司",
        "drug_interactions": '["含麻黄成分中成药避免与MAO抑制剂同用", "含甘草成分中成药长期使用需监测血压和血钾"]',
        "age_restrictions": '{"min": 3}',
        "drugs": [
            {
                "name": "板蓝根颗粒",
                "generic_name": "isatidis radix granules",
                "strength": "5g/袋",
                "dosage_form": "颗粒剂",
                "indications": ["感冒","咽喉痛","喉咙痛","发热","扁桃体炎"],
                "is_prescription": False, "price": 12.0,
                "min_stock": 60, "max_stock": 300,
            },
            {
                "name": "连花清瘟胶囊",
                "generic_name": "lianhua qingwen capsule",
                "strength": "0.35g/粒",
                "dosage_form": "胶囊",
                "indications": ["感冒","流感","发热","咳嗽","咽喉痛","头痛","肌肉痛"],
                "is_prescription": False, "price": 25.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "感冒灵颗粒",
                "generic_name": "ganmaoling granules",
                "strength": "10g/袋",
                "dosage_form": "颗粒剂",
                "indications": ["感冒","发热","头痛","咳嗽","流鼻涕","鼻塞","咽喉痛"],
                "is_prescription": False, "price": 15.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "蒲地蓝消炎口服液",
                "generic_name": "pudilan anti-inflammatory oral liquid",
                "strength": "10ml/支",
                "dosage_form": "口服液",
                "indications": ["咽喉痛","扁桃体炎","腮腺炎","感冒","发热"],
                "is_prescription": False, "price": 30.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "藿香正气水",
                "generic_name": "huoxiang zhengqi water",
                "strength": "10ml/支",
                "dosage_form": "口服液",
                "indications": ["中暑","肠胃不适","腹泻","恶心","呕吐","感冒","腹胀"],
                "is_prescription": False, "price": 10.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "六味地黄丸",
                "generic_name": "liuwei dihuang pill",
                "strength": "9g/丸",
                "dosage_form": "蜜丸",
                "indications": ["肾虚","腰膝酸软","头晕","耳鸣","盗汗","疲劳"],
                "is_prescription": False, "price": 25.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "牛黄解毒片",
                "generic_name": "niuhuang jiedu tablet",
                "strength": "0.27g/片",
                "dosage_form": "片剂",
                "indications": ["咽喉痛","口腔溃疡","牙龈炎","便秘","上火","牙痛"],
                "is_prescription": False, "price": 8.0,
                "min_stock": 50, "max_stock": 200,
            },
            {
                "name": "云南白药",
                "generic_name": "yunnan baiyao",
                "strength": "4g/瓶",
                "dosage_form": "散剂",
                "indications": ["跌打损伤","扭伤","瘀伤","肌肉痛","关节痛","出血"],
                "is_prescription": False, "price": 35.0,
                "min_stock": 25, "max_stock": 100,
            },
            {
                "name": "清开灵颗粒",
                "generic_name": "qingkailing granules",
                "strength": "6g/袋",
                "dosage_form": "颗粒剂",
                "indications": ["感冒","发热","咽喉痛","咳嗽","扁桃体炎"],
                "is_prescription": False, "price": 18.0,
                "min_stock": 30, "max_stock": 120,
            },
            {
                "name": "小柴胡颗粒",
                "generic_name": "xiaochaihu granules",
                "strength": "10g/袋",
                "dosage_form": "颗粒剂",
                "indications": ["感冒","发热","恶心","食欲不振","咽喉痛","头痛"],
                "is_prescription": False, "price": 15.0,
                "min_stock": 30, "max_stock": 120,
            },
        ],
    },
    {
        "category": "其他专科药",
        "manufacturer": "上海复旦张江生物医药股份有限公司",
        "drug_interactions": '["环孢素与多种药物有复杂相互作用，需专科医师指导", "秋水仙碱与大环内酯类抗生素同用需谨慎"]',
        "age_restrictions": '{"min": 18}',
        "drugs": [
            {
                "name": "黄体酮",
                "generic_name": "progesterone",
                "strength": "100mg",
                "dosage_form": "胶囊",
                "indications": ["月经不调","保胎","更年期综合征","功能性子宫出血"],
                "is_prescription": True, "price": 40.0,
                "min_stock": 15, "max_stock": 60,
            },
            {
                "name": "碳酸钙",
                "generic_name": "calcium carbonate",
                "strength": "500mg",
                "dosage_form": "片剂",
                "indications": ["骨质疏松","钙缺乏","抽筋","胃酸过多","骨折"],
                "is_prescription": False, "price": 20.0,
                "min_stock": 40, "max_stock": 150,
            },
            {
                "name": "硫糖铝",
                "generic_name": "sucralfate",
                "strength": "0.25g",
                "dosage_form": "片剂",
                "indications": ["胃痛","胃酸","胃溃疡","胃炎","胃食管反流"],
                "is_prescription": False, "price": 12.0,
                "min_stock": 30, "max_stock": 100,
            },
            {
                "name": "环孢素",
                "generic_name": "cyclosporine",
                "strength": "100mg",
                "dosage_form": "胶囊",
                "indications": ["移植排斥","类风湿关节炎","肾病综合征","银屑病","皮炎"],
                "is_prescription": True, "price": 120.0,
                "min_stock": 5, "max_stock": 20,
            },
            {
                "name": "秋水仙碱",
                "generic_name": "colchicine",
                "strength": "0.5mg",
                "dosage_form": "片剂",
                "indications": ["痛风","关节痛","急性痛风发作","痛风性关节炎"],
                "is_prescription": True, "price": 15.0,
                "min_stock": 15, "max_stock": 60,
            },
        ],
    },
]


def seed_database():
    """清空旧数据，重新生成 100+ 种药品"""
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # 清空旧数据（先删子表，再删主表）
    c.execute("DELETE FROM drug_indications")
    c.execute("DELETE FROM inventory")

    # 预生成货位坐标（最多 1000 个组合）
    shelf_positions = list(itertools.product(range(10), range(10), range(10)))

    drug_id = 0
    total_drugs = 0
    seed_ts = _utc_now_iso()

    # 第一周：更新 INSERT 以包含扩展字段
    for category_info in DRUG_CATEGORIES:
        category = category_info["category"]
        cat_manufacturer = category_info.get("manufacturer", "")
        cat_drug_interactions = category_info.get("drug_interactions", "[]")
        cat_age_restrictions = category_info.get("age_restrictions", "{}")

        for drug in category_info["drugs"]:
            drug_id += 1
            x, y, z = shelf_positions[(drug_id - 1) % len(shelf_positions)]

            quantity = random.randint(drug["min_stock"], drug["max_stock"])
            expiry_date = random.randint(365, 800)  # 一年以上有效期
            is_prescription = 1 if drug["is_prescription"] else 0
            price = float(drug["price"])
            indications = drug.get("indications") or []
            first_ind = indications[0] if indications else ""
            description = (
                f"适用于{first_ind}等相关症状的常用药品，请按说明书或医嘱使用。"
                if first_ind
                else "请按说明书或医嘱使用。"
            )
            cost_price = round(price * 0.65, 2)
            min_stock_alert = max(5, drug["min_stock"] // 2)

            # 第一周：新增扩展字段取值
            generic_name = drug.get("generic_name", "")
            strength = drug.get("strength", "")
            dosage_form = drug.get("dosage_form", "片剂")
            manufacturer = cat_manufacturer
            drug_interactions = cat_drug_interactions
            age_restrictions = cat_age_restrictions
            min_stock_level = drug["min_stock"]
            max_stock_level = drug["max_stock"]
            purchase_price = cost_price

            c.execute(
                """
                INSERT INTO inventory (
                    drug_id, name, quantity, expiry_date, shelf_x, shelf_y, shelve_id,
                    category, is_prescription, retail_price, stock,
                    generic_name, description, manufacturer, specification, dosage_form,
                    unit, pack_size, approval_number, barcode, storage_condition,
                    usage_dosage, contraindications, side_effects, interaction_warning,
                    pregnancy_category, pediatric_caution, supplier, country_of_origin,
                    cost_price, min_stock_alert, image_url,
                    is_deleted, created_at, updated_at,
                    strength, drug_interactions, age_restrictions,
                    min_stock_level, max_stock_level, purchase_price
                ) VALUES (
                    ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?
                )
                """,
                (
                    drug_id,
                    drug["name"],
                    quantity,
                    expiry_date,
                    x,
                    y,
                    z,
                    category,
                    is_prescription,
                    price,
                    0,
                    generic_name,
                    description,
                    manufacturer,
                    "",
                    dosage_form,
                    "盒",
                    "",
                    "",
                    "",
                    "密封，置阴凉干燥处",
                    "口服，详见说明书或遵医嘱。",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    cost_price,
                    min_stock_alert,
                    "",
                    0,
                    seed_ts,
                    seed_ts,
                    strength,
                    drug_interactions,
                    age_restrictions,
                    min_stock_level,
                    max_stock_level,
                    purchase_price,
                ),
            )

            for indication in drug["indications"]:
                c.execute("""
                    INSERT INTO drug_indications (drug_id, indication) VALUES (?, ?)
                """, (drug_id, indication))

            total_drugs += 1

    conn.commit()
    conn.close()
    print(f"Seeding complete: {total_drugs} drugs inserted across {len(DRUG_CATEGORIES)} categories.")


if __name__ == "__main__":
    seed_database()
