//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Task
{
    [Serializable]
    public class CabinetOrderMsg : Message
    {
        public const string k_RosMessageName = "task_msgs/CabinetOrder";
        public override string RosMessageName => k_RosMessageName;

        //  CabinetOrder.msg
        public string cabinet_id;
        public MedicineDataMsg[] medicine_list;

        public CabinetOrderMsg()
        {
            this.cabinet_id = "";
            this.medicine_list = new MedicineDataMsg[0];
        }

        public CabinetOrderMsg(string cabinet_id, MedicineDataMsg[] medicine_list)
        {
            this.cabinet_id = cabinet_id;
            this.medicine_list = medicine_list;
        }

        public static CabinetOrderMsg Deserialize(MessageDeserializer deserializer) => new CabinetOrderMsg(deserializer);

        private CabinetOrderMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cabinet_id);
            deserializer.Read(out this.medicine_list, MedicineDataMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cabinet_id);
            serializer.WriteLength(this.medicine_list);
            serializer.Write(this.medicine_list);
        }

        public override string ToString()
        {
            return "CabinetOrderMsg: " +
            "\ncabinet_id: " + cabinet_id.ToString() +
            "\nmedicine_list: " + System.String.Join(", ", medicine_list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
