//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Task
{
    [Serializable]
    public class CarStateMsg : Message
    {
        public const string k_RosMessageName = "task_msgs/CarState";
        public override string RosMessageName => k_RosMessageName;

        // CarState.msg
        public byte car_id;
        public float x;
        public float y;
        public byte isrunning;

        public CarStateMsg()
        {
            this.car_id = 0;
            this.x = 0.0f;
            this.y = 0.0f;
            this.isrunning = 0;
        }

        public CarStateMsg(byte car_id, float x, float y, byte isrunning)
        {
            this.car_id = car_id;
            this.x = x;
            this.y = y;
            this.isrunning = isrunning;
        }

        public static CarStateMsg Deserialize(MessageDeserializer deserializer) => new CarStateMsg(deserializer);

        private CarStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.car_id);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.isrunning);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.car_id);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.isrunning);
        }

        public override string ToString()
        {
            return "CarStateMsg: " +
            "\ncar_id: " + car_id.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nisrunning: " + isrunning.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
