//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Task
{
    [Serializable]
    public class TaskStateMsg : Message
    {
        public const string k_RosMessageName = "task_msgs/TaskState";
        public override string RosMessageName => k_RosMessageName;

        // TaskState.msg
        public string taskid;
        public int task_state;
        public int car_id;

        public TaskStateMsg()
        {
            this.taskid = "";
            this.task_state = 0;
            this.car_id = 0;
        }

        public TaskStateMsg(string taskid, int task_state, int car_id)
        {
            this.taskid = taskid;
            this.task_state = task_state;
            this.car_id = car_id;
        }

        public static TaskStateMsg Deserialize(MessageDeserializer deserializer) => new TaskStateMsg(deserializer);

        private TaskStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.taskid);
            deserializer.Read(out this.task_state);
            deserializer.Read(out this.car_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.taskid);
            serializer.Write(this.task_state);
            serializer.Write(this.car_id);
        }

        public override string ToString()
        {
            return "TaskStateMsg: " +
            "\ntaskid: " + taskid.ToString() +
            "\ntask_state: " + task_state.ToString() +
            "\ncar_id: " + car_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
